version: '3'

services:

  tunnel-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/slick-portfolio-svelte/src
    ports:
      - "3001:3000"
    command: ["npm", "run", "dev"]
    environment:
      - VITE_ENV=development
    networks:
      - main

  tunnel-static-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:80"
    environment:
      - VITE_ENV=production
    networks:
      - main

networks:
  main:
    driver: bridge